const actionTypes = {
  GET_LOCATIONLIST: "GET_LOCATIONLIST",
  GET_ROOMLIST: "GET_ROOMLIST",
  GET_ROOM_DETAIL: "GET_ROOM_DETAIL",
  GET_REVIEW_LIST: "GET_REVIEW_LIST",
  SET_BOOKING_DATE: "SET_BOOKING_DATE",
  SET_BOOKING_DAYS: "SET_BOOKING_DAYS",
  SET_BOOKING_GUEST: "SET_BOOKING_GUEST",
  POST_BOOKING_LIST: "POST_BOOKING_LIST",
  SET_USER_LOGIN: "SET_USER_LOGIN",
};

export default actionTypes;
